services:
  backend:
    container_name: backend
    restart: always
    image: backend:develop
    build: ./backend
    volumes:
      - ./backend:/app  # On monte le dossier backend, pas toute la racine du projet
      - node_modules:/app/node_modules  # Pour éviter les conflits de node_modules
    ports:
      - '3333:3333'
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: myplex_user
      POSTGRES_PASSWORD: myplex_password
      POSTGRES_DB: myplex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
  node_modules:
  app:
